apiVersion: v2
name: kronic
description: Kronic - The simple Kubernetes CronJob Admin UI
type: application
version: 0.1.3
appVersion: "v0.1.0"
home: https://github.com/mshade/kronic
maintainers:
  - name: mshade
    email: mshade@mshade.org
    url: https://github.com/mshade
annotations:
  artifacthub.io/category: monitoring-logging
